services:
  reverse-proxy:
    build: ./nginx_proxy_server
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
