services:
  reverse-proxy:
    build: ./nginx_proxy_server
    ports:
      - "80:80"
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    