services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "443:443"  # Exposing the HTTPS port
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
