lessons = [
  {
    "id": 1,
    "title": "Home Row - Part 1",
    "description": "Introduction to the home row keys on the Colemak keyboard layout.",
    "difficulty": "Easy",
    "keys": "arstdhneio",
    "words": [
      "ar",
      "as",
      "at",
      "an",
      "ah",
      "ad",
      "ae",
      "ea",
      "en",
      "et",
      "er",
      "ed",
      "es",
      "he",
      "ha",
      "hi",
      "it",
      "is",
      "in",
      "no",
      "on",
      "oh",
      "or",
      "ot",
      "to",
      "the",
      "and",
      "her",
      "his",
      "has",
      "had",
      "its",
      "hit",
      "sit",
      "sin",
      "son",
      "not",
      "one",
      "note"
    ]
  },
  {
    "id": 2,
    "title": "Home Row - Part 2",
    "description": "More practice with the home row keys on the Colemak keyboard layout.",
    "difficulty": "Easy",
    "keys": "arstdhneio",
    "words": [
      "read",
      "near",
      "dare",
      "rise",
      "seat",
      "sand",
      "send",
      "tide",
      "tide",
      "soar",
      "hear",
      "nose",
      "rise",
      "road",
      "hand",
      "nest",
      "idea",
      "done",
      "note",
      "tone",
      "earn",
      "note",
      "tear",
      "hear",
      "said",
      "tide",
      "tend",
      "hast",
      "hair",
      "hate"
    ]
  },
  {
    "id": 3,
    "title": "Top Row - Part 1",
    "description": "Introduction to the top row keys on the Colemak keyboard layout.",
    "difficulty": "Medium",
    "keys": "qwfpbjluy",
    "words": [
      "quit",
      "will",
      "fall",
      "pull",
      "bull",
      "full",
      "luck",
      "walk",
      "july",
      "joke",
      "jail",
      "bulk",
      "bump",
      "wall",
      "puff",
      "pack",
      "jump",
      "yell",
      "yolk",
      "yard",
      "quiz",
      "quill",
      "flap",
      "flip",
      "flow",
      "flag",
      "plot",
      "play",
      "blip",
      "blow"
    ]
  },
  {
    "id": 4,
    "title": "Bottom Row - Part 1",
    "description": "Introduction to the bottom row keys on the Colemak keyboard layout.",
    "difficulty": "Medium",
    "keys": "zxcmv",
    "words": [
      "zoom",
      "zone",
      "zinc",
      "zany",
      "zaps",
      "cats",
      "camp",
      "clamp",
      "clap",
      "clam",
      "clan",
      "vamp",
      "vase",
      "vast",
      "vane",
      "vice",
      "vain",
      "vest",
      "vent",
      "vent",
      "view",
      "vine",
      "vows",
      "cave",
      "move",
      "mock",
      "kick",
      "mask",
      "task",
      "moss"
    ]
  },
  {
    "id": 5,
    "title": "All Rows Combined - Part 1",
    "description": "Practice typing with a combination of home row, top row, and bottom row keys.",
    "difficulty": "Hard",
    "keys": "arstdhneioqwfpbjluyzxcmv",
    "words": [
      "quick",
      "brown",
      "fox",
      "jumps",
      "over",
      "lazy",
      "dog",
      "jazz",
      "buzz",
      "fizz",
      "fuzzy",
      "quiz",
      "puzzled",
      "jumping",
      "jack",
      "happy",
      "hex",
      "kickboxing",
      "vexed",
      "wizard",
      "blizzard",
      "crazy",
      "puzzle",
      "klutz",
      "frozen",
      "sphinx",
      "dizzy",
      "fizzy",
      "joking",
      "pack"
    ]
  }
]
